# Clustering & the K-Means

Clustering is a fundamental unsupervised learning technique used to group data points based on similarity. Unlike supervised learning, where both inputs and target labels are provided, clustering relies solely on input data to uncover hidden structures and patterns.

Clustering is the process of partitioning a dataset into groups (or clusters) such that:
- **Intra-cluster similarity** is high: Data points in the same cluster are similar to each other.
- **Inter-cluster similarity** is low: Data points in different clusters are dissimilar.

### **Contrast with Supervised Learning**

- **Supervised Learning:**  
  You have input features ($x$) and corresponding labels ($y$). The model learns a mapping from $x$ to $y$, such as in binary classification where you might use logistic regression or neural networks to find a decision boundary.

- **Unsupervised Learning (Clustering):**  
  Only the features $x$ are provided. There is no “correct” answer given. Instead, the algorithm must infer structure, grouping similar data points together. When visualized, the dataset is simply a collection of dots, without predefined classes.

### **Real-World Examples of Clustering**

- **News Article Grouping:** Automatically grouping similar news articles (e.g., technology, sports, politics).
- **Market Segmentation:** Categorizing customers or learners based on behaviors or preferences.
- **Genetic Analysis:** Grouping individuals based on DNA expression data to identify similar genetic traits.
- **Astronomy:** Grouping celestial bodies to identify galaxies or detect patterns in space.
- **Image Compression:** Reducing the number of colors in an image by clustering similar color values.

---

## The K-Means Clustering Algorithm

K-means is one of the simplest and most widely used clustering algorithms. Its goal is to partition a dataset into **K clusters** by minimizing the variance within each cluster.

K-means works iteratively through two primary steps:

### **Step A: Assignment (Cluster Membership)**
1. **Initialization:**  
   Randomly choose $K$ data points as the initial cluster centroids:

$$\mu_1, \mu_2, \dots, \mu_K$$

   These centroids are vectors with the same dimensions as the data points. They represent the "center" of each cluster.

2. **Assign Points to Nearest Centroid:**  
   For each data point $x^{(i)}$, determine its closest centroid using the squared Euclidean distance. Mathematically, assign:

$$C^{(i)} = \arg\min_{k} \| x^{(i)} - \mu_k \|^2$$

   where $C^{(i)}$ is the cluster index (from 1 to $K$) for the data point $x^{(i)}$.

### **Step B: Update (Centroid Recalculation)**
1. **Recompute Centroids:**  
   After assigning every point to a cluster, update each centroid by computing the mean (average) of all data points assigned to that cluster:

$$\mu_k = \frac{1}{|S_k|} \sum_{x^{(i)} \in S_k} x^{(i)}$$

   where $S_k$ is the set of points assigned to cluster $k$.

2. **Repeat Until Convergence:**  
   Alternate between the assignment and update steps. Convergence is reached when the centroids no longer move significantly, or when the cluster assignments stop changing.


### **Handling Special Cases**
- **Empty Cluster:**  
  If a centroid ends up with no points assigned (i.e., $S_k$ is empty), you can:
  - **Eliminate the cluster,** reducing $K$, or
  - **Reinitialize the centroid** randomly to hope it captures a new group in the next iteration.

---

## The Cost (Distortion) Function

K-means optimizes a cost function that quantifies the “tightness” of clusters. This cost function, often called the **distortion function**, is defined as:

$$
J(C, \mu) = \frac{1}{m} \sum_{i=1}^{m} \| x^{(i)} - \mu_{C^{(i)}} \|^2
$$

- **Interpretation:**  
  For each data point, calculate the squared distance to its assigned centroid, sum these values for all points, and take the average. A lower $J$ indicates that points are closer to their centroids, which implies better clustering.

- **Optimization:**  
  - **Assignment Step:** Minimizes $J$ with respect to the cluster assignments $C^{(i)}$, keeping $\mu_k$ fixed.
  - **Update Step:** Minimizes $J$ with respect to the centroids $\mu_k$, keeping $C^{(i)}$ fixed.

Because each iterative step is designed to reduce (or at worst, not increase) $J$, the algorithm is guaranteed to converge to a local minimum of the cost function.

---

## Enhancing K-Means: Advanced Considerations

### **Multiple Random Initializations**
- **Problem:**  
  A poor initial guess may lead to a local optimum that does not represent the best clustering.
- **Solution:**  
  Run K-means several times (often 50–1000 iterations) with different random starting centroids. For each run, compute the cost function $J$. Select the clustering result with the lowest $J$ as the final solution.

### **Choosing the Number of Clusters, $K$**
- **Ambiguity:**  
  In many datasets, the "true" number of clusters is not obvious.
- **Elbow Method:**  
  Run K-means for a range of $K$ values and plot the cost function $J$ against $K$. Look for an "elbow" in the curve where the rate of decrease sharply slows—this can be a heuristic for the optimal $K$.
- **Application-Driven:**  
  The choice of $K$ might depend on downstream tasks. For example:
  - **T-Shirt Sizing:**  
    Three clusters might correspond to small, medium, and large sizes. Five clusters could allow extra small and extra large options, balancing fit quality with manufacturing costs.
  - **Image Compression:**  
    More clusters mean higher image quality but less compression. Fewer clusters yield higher compression at the cost of quality.

### **Initialization Techniques**
- **K-means++:**  
  An enhancement over random initialization, K-means++ spreads out the initial centroids to reduce the chances of poor clustering and speed up convergence.

### **Limitations of K-Means**
- **Cluster Shape:**  
  K-means assumes clusters are spherical (or convex) and similar in size. It may perform poorly if clusters are irregularly shaped or vary widely in density.
- **Scaling:**  
  Since the algorithm is based on distance measurements, feature scaling (e.g., standardization) is crucial.
- **Local Optima:**  
  K-means can get stuck in local minima, making multiple initializations necessary.

---

## Implementation Details and Practical Tips

### **Algorithm Pseudocode**

```pseudo
Initialize centroids μ₁, μ₂, ..., μₖ randomly (or using K-means++)
Repeat until convergence:
    For each data point x⁽ⁱ⁾:
        Assign C⁽ⁱ⁾ = argminₖ || x⁽ⁱ⁾ - μₖ ||²
    For each cluster k:
        Update μₖ = average of all x⁽ⁱ⁾ with C⁽ⁱ⁾ = k
```

### **Cost Function Monitoring**
- **Convergence Test:**  
  Monitor the cost function $J$. If it stops decreasing (or decreases very slowly), the algorithm has likely converged.
- **Debugging:**  
  If $J$ increases at any step, it is a sign of an implementation error.

### **Real-World Application Example: Image Compression**
- **How It Works:**  
  Each pixel's color is treated as a data point in a color space (e.g., RGB). K-means groups similar colors together, and each pixel is then approximated by the nearest centroid.
- **Trade-Off:**  
  More clusters mean the compressed image is closer to the original, but requires more storage for the color palette. Fewer clusters lead to greater compression but may result in noticeable quality loss.

---

## Summary and Key Takeaways

- **Clustering** is a method for discovering groups within unlabeled data.
- **K-means** is an iterative algorithm that partitions data into $K$ clusters by alternating between:
  - **Assignment:** Assigning each data point to its nearest centroid.
  - **Update:** Recalculating centroids as the mean of the points in each cluster.
- The algorithm minimizes a **cost function** (distortion function), defined as the average squared distance between data points and their assigned centroids.
- **Advanced considerations** include running multiple random initializations, choosing $K$ via methods like the elbow method, and enhancements such as K-means++.
- **Limitations:** K-means works best for spherical, equally sized clusters and is sensitive to feature scaling and initial conditions.

In [1]:
import numpy as np

In [50]:
def closest_centroids(X, centroids):
    """
    Finds closest centroids for each example (centroid memberships)
    """

    m = X.shape[0]
    c = np.zeros(m, dtype=int)
    
    for i in range(m):
        distance = np.linalg.norm(X[i] - centroids, axis=1)
        c[i] = np.argmin(distance)

    return c

In [51]:
def compute_centroids(X, idx, K):
    """
    Returns the new centroids by computing the means of the data points assigned to each centroid.
    """

    m, n = X.shape
    centroids = np.zeros((K, n))
    for i in range(K):
        assigned_points = X[idx == i]
        centroids[i] = assigned_points.mean(axis=0)

    return centroids

In [52]:
X = np.random.rand(100, 3)
K = 2
centroids = X[np.random.choice(X.shape[0], 2, replace=False)]
centroids

array([[0.049447  , 0.61960541, 0.93058769],
       [0.42083364, 0.03107269, 0.59460929]])

In [53]:
idx = closest_centroids(X, centroids)
idx

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1])

In [54]:
compute_centroids(X, idx, K)

array([[0.38295948, 0.73068537, 0.59095699],
       [0.650836  , 0.34213095, 0.42198745]])

In [59]:
def run_K_means(X, K, epoches=10):
    centroids = X[np.random.choice(X.shape[0], K, replace=False)]

    for i in range(epoches):
        print(f"Epoch {i} centroids\n{centroids}")
        idx = closest_centroids(X, centroids)
        centroids = compute_centroids(X, idx, K)

In [61]:
run_K_means(X, 3, 5)

Epoch 0 centroids
[[0.86066761 0.21041536 0.91281784]
 [0.51338367 0.22955841 0.11319952]
 [0.73085486 0.45740573 0.9664677 ]]
Epoch 1 centroids
[[0.88653784 0.14526024 0.76230481]
 [0.47674229 0.46075878 0.29342756]
 [0.57165463 0.64431242 0.73548996]]
Epoch 2 centroids
[[0.83786685 0.13568814 0.63108646]
 [0.44829065 0.49070073 0.29235112]
 [0.5596594  0.68242022 0.73189871]]
Epoch 3 centroids
[[0.81319218 0.16515631 0.56841341]
 [0.42347371 0.51535751 0.28868982]
 [0.54325358 0.69859217 0.73258859]]
Epoch 4 centroids
[[0.76705413 0.1947748  0.54074485]
 [0.39101969 0.55859692 0.27347455]
 [0.55249433 0.70263744 0.74683255]]
